export declare const theme: {
    typography: {
        lineHeight: string;
    };
    fonts: {
        family: {
            base: string;
            accent: string;
        };
        weight: {
            regular: number;
            medium: number;
            semiBold: number;
            bold: number;
        };
        size: {
            base: string;
            h1: string;
            h2: string;
            h3: string;
            h4: string;
            h5: string;
            p: string;
        };
        color: {};
    };
    breakpoints: {
        readonly smallMobile: "320px";
        readonly mobile: "425px";
        readonly largeMobile: "576px";
        readonly tablet: "768px";
        readonly computer: "992px";
        readonly desktop: "1200px";
        readonly widescreen: "1400px";
        readonly extraWidescreen: "1920px";
    };
    mediaMinWidth: {
        smallMobile: string;
        mobile: string;
        largeMobile: string;
        tablet: string;
        computer: string;
        desktop: string;
        widescreen: string;
        extraWidescreen: string;
    };
    mediaMaxWidth: {
        smallMobile: string;
        mobile: string;
        largeMobile: string;
        tablet: string;
        computer: string;
        desktop: string;
        widescreen: string;
        extraWidescreen: string;
    };
    duration: {
        long: string;
        middle: string;
        short: string;
    };
    zIndices: {
        modal: number;
        tooltip: number;
        dropdown: number;
        header: number;
        footer: number;
        mainContent: number;
    };
    shadow: {
        full: string;
        right: string;
    };
    hrefs: {
        tel: string;
    };
    colors: {
        primary: string;
        secondary: string;
        bg_primary: string;
        white: string;
        white_smoke: string;
        gainsboro: string;
        lightGray: string;
        silver: string;
        gray: string;
        dimGray: string;
        darkGray: string;
        lightSlateGray: string;
        slateGray: string;
        darkSlateGray: string;
        dark: string;
        black: string;
        red: {
            b50: string;
            b100: string;
            b200: string;
            b300: string;
            b400: string;
            b500: string;
            b600: string;
            b700: string;
            b800: string;
            b900: string;
            ab100: string;
            ab200: string;
            ab400: string;
            ab700: string;
        };
        pink: {
            b50: string;
            b100: string;
            b200: string;
            b300: string;
            b400: string;
            b500: string;
            b600: string;
            b700: string;
            b800: string;
            b900: string;
            ab100: string;
            ab200: string;
            ab400: string;
            ab700: string;
        };
        purple: {
            b50: string;
            b100: string;
            b200: string;
            b300: string;
            b400: string;
            b500: string;
            b600: string;
            b700: string;
            b800: string;
            b900: string;
            ab100: string;
            ab200: string;
            ab400: string;
            ab700: string;
        };
        deeppurple: {
            b50: string;
            b100: string;
            b200: string;
            b300: string;
            b400: string;
            b500: string;
            b600: string;
            b700: string;
            b800: string;
            b900: string;
            ab100: string;
            ab200: string;
            ab400: string;
            ab700: string;
        };
        indigo: {
            b50: string;
            b100: string;
            b200: string;
            b300: string;
            b400: string;
            b500: string;
            b600: string;
            b700: string;
            b800: string;
            b900: string;
            ab100: string;
            ab200: string;
            ab400: string;
            ab700: string;
        };
        blue: {
            b50: string;
            b100: string;
            b200: string;
            b300: string;
            b400: string;
            b500: string;
            b600: string;
            b700: string;
            b800: string;
            b900: string;
            ab100: string;
            ab200: string;
            ab400: string;
            ab700: string;
        };
        lightblue: {
            b50: string;
            b100: string;
            b200: string;
            b300: string;
            b400: string;
            b500: string;
            b600: string;
            b700: string;
            b800: string;
            b900: string;
            ab100: string;
            ab200: string;
            ab400: string;
            ab700: string;
        };
        cyan: {
            b50: string;
            b100: string;
            b200: string;
            b300: string;
            b400: string;
            b500: string;
            b600: string;
            b700: string;
            b800: string;
            b900: string;
            ab100: string;
            ab200: string;
            ab400: string;
            ab700: string;
        };
        teal: {
            b50: string;
            b100: string;
            b200: string;
            b300: string;
            b400: string;
            b500: string;
            b600: string;
            b700: string;
            b800: string;
            b900: string;
            ab100: string;
            ab200: string;
            ab400: string;
            ab700: string;
        };
        green: {
            b50: string;
            b100: string;
            b200: string;
            b300: string;
            b400: string;
            b500: string;
            b600: string;
            b700: string;
            b800: string;
            b900: string;
            ab100: string;
            ab200: string;
            ab400: string;
            ab700: string;
        };
        lightgreen: {
            b50: string;
            b100: string;
            b200: string;
            b300: string;
            b400: string;
            b500: string;
            b600: string;
            b700: string;
            b800: string;
            b900: string;
            ab100: string;
            ab200: string;
            ab400: string;
            ab700: string;
        };
        lime: {
            b50: string;
            b100: string;
            b200: string;
            b300: string;
            b400: string;
            b500: string;
            b600: string;
            b700: string;
            b800: string;
            b900: string;
            ab100: string;
            ab200: string;
            ab400: string;
            ab700: string;
        };
        yellow: {
            b50: string;
            b100: string;
            b200: string;
            b300: string;
            b400: string;
            b500: string;
            b600: string;
            b700: string;
            b800: string;
            b900: string;
            ab100: string;
            ab200: string;
            ab400: string;
            ab700: string;
        };
        amber: {
            b50: string;
            b100: string;
            b200: string;
            b300: string;
            b400: string;
            b500: string;
            b600: string;
            b700: string;
            b800: string;
            b900: string;
            ab100: string;
            ab200: string;
            ab400: string;
            ab700: string;
        };
        orange: {
            b50: string;
            b100: string;
            b200: string;
            b300: string;
            b400: string;
            b500: string;
            b600: string;
            b700: string;
            b800: string;
            b900: string;
            ab100: string;
            ab200: string;
            ab400: string;
            ab700: string;
        };
        deeporange: {
            b50: string;
            b100: string;
            b200: string;
            b300: string;
            b400: string;
            b500: string;
            b600: string;
            b700: string;
            b800: string;
            b900: string;
            ab100: string;
            ab200: string;
            ab400: string;
            ab700: string;
        };
        brown: {
            b50: string;
            b100: string;
            b200: string;
            b300: string;
            b400: string;
            b500: string;
            b600: string;
            b700: string;
            b800: string;
            b900: string;
        };
        grey: {
            b50: string;
            b100: string;
            b200: string;
            b300: string;
            b400: string;
            b500: string;
            b600: string;
            b700: string;
            b800: string;
            b900: string;
        };
        bluegrey: {
            b50: string;
            b100: string;
            b200: string;
            b300: string;
            b400: string;
            b500: string;
            b600: string;
            b700: string;
            b800: string;
            b900: string;
        };
    };
};
